Socialize/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    
    path('', auth_views.LoginView.as_view(template_name="login.html"),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
    path('home/', views.HomePage.as_view(), name="home"),
    path('thanks/', views.ThanksPage.as_view(), name="thanks"),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('posts/', include("posts.urls", namespace="posts")),
    path('groups/',include("groups.urls", namespace="groups")),
]

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name="signup"),
]

posts/urls.py
from django.urls import path
from . import views

app_name='posts'
 
urlpatterns = [
    path('', views.PostList.as_view(), name="all"),
    # path('home/', views.HomePage.as_view(), name="home"),
    path("new/", views.CreatePost.as_view(), name="create"),
    path("by/<username>/",views.UserPosts.as_view(),name="for_user"),
    path("by/<username>/<int:pk>/",views.PostDetail.as_view(),name="single"),
    path("delete/<int:pk>/",views.DeletePost.as_view(),name="delete"),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap4 %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Socialize</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link href="static/css/master.css" rel="stylesheet">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-dark mynav" role="navigation" id="navbar">
      <div class="container">
        <div class="navbar-nav align-items-center">
          <a class="navbar-brand mynav" href="{% url 'home' %}">Socialize</a>
        </div>
        <div class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'posts:create' %}" class="btn btn-simple">Post</a>
            <a class="nav-item nav-link" href="{% url 'groups:all' %}" class="btn btn-simple">Groups</a>
            <a class="nav-item nav-link" href="{% url 'groups:create' %}" class="btn btn-simple">Create Group</a>
            <a class="nav-item nav-link" href="{% url 'logout' %}" class="btn btn-simple">Log out</a>
          {% else %}
            <a class="nav-item nav-link" href="{% url 'groups:all' %}"class="btn btn-simple">Groups</a>
            
          {% endif %}
        </div>
      </div>
    </nav>

    <div class="container">
      {% block content %}

      {% endblock %}
    </div>

    <canvas id="canvas"></canvas>

  </body>
</html>

templates/home.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <h1>You are now logged in!</h1>
  <h2><a href="{% url 'groups:all'%}">Go to Groups</a></h2>

</div>

{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block content %}

    <h1>Welcome to Star Social!</h1>

{% endblock %}

templates/login.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap4 %}
<html>
    <head>
            <meta charset="utf-8">
            <title>Socialize</title>
        
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
            integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        
            <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
        
            <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
        
            <link href="static/css/master.css" rel="stylesheet">

    </head>
    <body>
        <div class="container">

            <div>
               <img src="static/logo-Socialize-image.png" id="image"> 
            </div>

            <div>
                <p class='login-page-text'>
                    Welcome to Socialize! <br> Meet people with similar interests
                </p>
            </div>

            <div>
                <p class='login-page-text'>Not a user?</p>
                    <a href="{% url 'accounts:signup' %}" class="btn btn-light" style="color:white; background-color: #00796B;">
                        Sign Up
                    </a>
            </div>

            <div class='module-wrap'>
                <div id='login-block'>
                    <h1>Log In</h1>
                    <form method="POST" class="form">
                        {% csrf_token %}
                        {% bootstrap_form form %}
                        {% buttons %}
                            <button type="submit" class="btn btn-light" style="background-color: #00796B; color:white;">
                                Log In
                            </button>
                        {% endbuttons %}
                    </form>
                </div>

            </div>
            
          </div>
    </body>
</html>

templates/test.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <h1>You are now logged in!</h1>
  <h2><a href="{% url 'groups:all'%}">Go to Groups</a></h2>

</div>

{% endblock %}

templates/thanks.html
{% extends "base.html" %}
{% block content %}
<h1>Thanks for visiting! Come back soon!</h1>

{% endblock %}